//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/openup_lifecycle_EE511F3A_ee511f3a_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Inception Phase_5229EC90_ba040c1e_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_3s7aYdONEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_8A8E7EA8_110117fc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Transition Phase_14EE9310_7cc8b29e_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4g,_CoJVUdOPEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_BCA6545C_9c50b5b0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_AP_nodOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_E4A7147_94bd0a9b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_CqFrgdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_2E5A12EB_b4ccac3f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4g,_uxDPEdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_91628C02_814b1317_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_GQejYdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_949DD70E_1b107062_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4g,_vyeP0dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_E06651D6_d04ed8eb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_62694d6_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4g,_-iix4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_8E22EA8F_6dcd4be3_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/inception_phase_iteration_1EFD4B4F_1e8aebc1_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_architecture_D0F73FC9_cd5de558_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_YwLY4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_38854BCF_34ebf15e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Elaboration Phase_F6EBBC8B_5ec5dc19_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/elaboration_phase_iteration_579A68CE_b288583b_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4g,_5v_o4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_1EC56795_fe6fc8e9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/transition_phase_iteration_9880C0E_29eed300_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_XayTQdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_947FDB8B_90e6811a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4g,_w-Bc8dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/agree_technical_approach_66972D77_567fb48c_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvwActivity"]="./../../process.openup.base/deliveryprocesses/resources/Construction Phase_BD0D5748_24e776d6_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_pOgXIVQwEd2i9JHp7xurvw,_7bg6EdOPEdyqlogshP8l4g,_AZ58IdOPEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_55FA17AC_35a47900_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_f4VuYdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_B552446C_b1b8e9fb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_g8cPsdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_6EA48E23_6b0b33b2_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4g,_HhjJsdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_48F8F25_8b022879_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_ieYHIVQwEd2i9JHp7xurvw,_51ewYdOPEdyqlogshP8l4g,_eyv_UdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_C9559260_c5bc37ef_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_nfpBkVQwEd2i9JHp7xurvw,_6togYdOPEdyqlogshP8l4gActivity"]="./../../process.openup.base/deliveryprocesses/resources/construction_phase_iteration_5BD4A7D6_fdf0b00_Activity.jpeg"
contentPage.processPage.imageFiles["_SuWj4dOPEdyqlogshP8l4g,_8tQrUVQvEd2i9JHp7xurvw,_kYVSUdOPEdyqlogshP8l4g,_nfpeAdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/initiate_project_9D7C8344_8d650a59_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_SKnA1uL9EdyM47cGD2jiaQActivity"]="./../../practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/resources/risk_value_lifecycle_phases_4D57D552_4d57d552_Activity.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4g,_uxDPEdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_91628C02_eed011a9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4g,_nfpeAdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/initiate_project_9D7C8344_faea08eb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/inception_phase_iteration_B1800053_b1800053_Activity.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4g,_w-Bc8dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/agree_technical_approach_66972D77_c404b31e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_h0Gs8dONEdyqlogshP8l4g,_vyeP0dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_E06651D6_3dd3d77d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_architecture_D0F73FC9_5db845c6_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_eyv_UdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_C9559260_5616985d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/elaboration_phase_iteration_54DFA2A9_54dfa2a9_Activity.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_XayTQdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_947FDB8B_2140e188_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_f4VuYdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_B552446C_42134a69_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_g8cPsdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_6EA48E23_fb659420_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_YwLY4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_38854BCF_c54651cc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_aUsVEdONEdyqlogshP8l4g,_aSrtcdOOEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_92220b44_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_3s7aYdONEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_8A8E7EA8_c43cb78_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_GQejYdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_949DD70E_165323de_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_CqFrgdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_2E5A12EB_b00f5fbb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_HhjJsdOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_48F8F25_8644dbf5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/construction_phase_iteration_9AC1727C_9ac1727c_Activity.jpeg"
contentPage.processPage.imageFiles["_RQi0AdONEdyqlogshP8l4g,_AP_nodOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_E4A7147_8fffbe17_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4g,_-iix4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_8E22EA8F_ee2c9098_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/transition_phase_iteration_57B0A6B5_57b0a6b5_Activity.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4g,_AZ58IdOPEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_55FA17AC_b603bdb5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4g,_CoJVUdOPEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_BCA6545C_1caffa65_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_pzQU0dONEdyqlogshP8l4g,_5v_o4dOOEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_1EC56795_7ecf0d9e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_xxcpgdOEEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/identify_and_refine_requirements_7FA6CB14_7fa6cb14_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_eWxZgdOEEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/initiate_project_37A47ADB_37a47adb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_4ouDUdOEEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/agree_technical_approach_7096F6A3_7096f6a3_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_oZgCsdOEEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/plan_manage_iteration_F9713A62_f9713a62_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_KaeNsdOFEdyqlogshP8l4g,_TV_k8dOKEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4A08A92A_5f3b39d9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_KaeNsdOFEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_architecture_C7BBA35B_c7bba35b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_RXGoodOFEdyqlogshP8l4gActivity"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4FBB0E6E_4fbb0e6e_Activity.jpeg"
contentPage.processPage.imageFiles["_RXGoodOFEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/develop_solution_4FBB0E6E_4fbb0e6e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_buG4sdOFEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/test_solution_D16D88FC_d16d88fc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["__ZInMdOEEdyqlogshP8l4gActivityDetail"]="./../../process.openup.base/capabilitypatterns/resources/ongoing_tasks_CA154C21_ca154c21_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_ePfxAFTiEd2ZeY-22kx0mw"] = ["Initial Operational Capability Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Initial Operational Capability_D87619F1.html"];
contentPage.processPage.elementUrls["_2_nRIVThEd2ZeY-22kx0mw"] = ["Elaboration Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Elaboration Phase_53DE05EC.html"];
contentPage.processPage.elementUrls["_gX7xQtOKEdyqlogshP8l4g"] = ["DeveloperTest","process.openup.base/capabilitypatterns/developer_test_DC61DB05.html"];
contentPage.processPage.elementUrls["_AVhA09OOEdyqlogshP8l4g"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_6B2E9CEB.html"];
contentPage.processPage.elementUrls["_RQi0AdONEdyqlogshP8l4g"] = ["Construction Phase Iteration","process.openup.base/capabilitypatterns/construction_phase_iteration_9AC1727C.html"];
contentPage.processPage.elementUrls["_AZ58IdOPEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_55FA17AC.html"];
contentPage.processPage.elementUrls["_AQJYqdOOEdyqlogshP8l4g"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_C4C69066.html"];
contentPage.processPage.elementUrls["_ieYHIVQwEd2i9JHp7xurvw"] = ["Elaboration Phase","process.openup.base/deliveryprocesses/Elaboration Phase_F6EBBC8B.html"];
contentPage.processPage.elementUrls["_6togYdOPEdyqlogshP8l4g"] = ["Construction Iteration [1..n]","process.openup.base/deliveryprocesses/construction_phase_iteration_5BD4A7D6.html"];
contentPage.processPage.elementUrls["_kYVSUdOPEdyqlogshP8l4g"] = ["Inception Iteration [1..n]","process.openup.base/deliveryprocesses/inception_phase_iteration_1EFD4B4F.html"];
contentPage.processPage.elementUrls["_3s7aYdONEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_8A8E7EA8.html"];
contentPage.processPage.elementUrls["_Ei9OcdOKEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_7B656A6B.html"];
contentPage.processPage.elementUrls["_Vi5r8NOLEdyqlogshP8l4g"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_50CC2DD7.html"];
contentPage.processPage.elementUrls["_soyUVNOJEdyqlogshP8l4g"] = ["Vision","process.openup.base/capabilitypatterns/vision_69999C5F.html"];
contentPage.processPage.elementUrls["_TV_k8dOKEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_4A08A92A.html"];
contentPage.processPage.elementUrls["_AVhA1NOOEdyqlogshP8l4g"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_CDAFB51F.html"];
contentPage.processPage.elementUrls["_EjG_cNOKEdyqlogshP8l4g"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_1EE52118.html"];
contentPage.processPage.elementUrls["_soyUUtOJEdyqlogshP8l4g"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_9E3EAE66.html"];
contentPage.processPage.elementUrls["_tzWYwNnFEdyNWvE4rz3mXQ"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_194926F3.html"];
contentPage.processPage.elementUrls["_h0Gs8dONEdyqlogshP8l4g"] = ["Inception Phase Iteration","process.openup.base/capabilitypatterns/inception_phase_iteration_B1800053.html"];
contentPage.processPage.elementUrls["_RXGoodOFEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_4FBB0E6E.html"];
contentPage.processPage.elementUrls["_HGqkMNnTEdyNj6EOmqy5Rg"] = ["Request Change","process.openup.base/capabilitypatterns/request_change_BA075BFE.html"];
contentPage.processPage.elementUrls["_t7pDUtOJEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_964DADA5.html"];
contentPage.processPage.elementUrls["_y05RQNOJEdyqlogshP8l4g"] = ["Plan Iteration","process.openup.base/capabilitypatterns/plan_iteration_B0421040.html"];
contentPage.processPage.elementUrls["_frh-QtOKEdyqlogshP8l4g"] = ["Design","process.openup.base/capabilitypatterns/design_B2747424.html"];
contentPage.processPage.elementUrls["_SKnAzuL9EdyM47cGD2jiaQ"] = ["Inception Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Inception Iteration 1..n_5AF15029.html"];
contentPage.processPage.elementUrls["_aUsVEdONEdyqlogshP8l4g"] = ["Elaboration Phase Iteration","process.openup.base/capabilitypatterns/elaboration_phase_iteration_54DFA2A9.html"];
contentPage.processPage.elementUrls["_gX7xQdOKEdyqlogshP8l4g"] = ["[Software Design]","process.openup.base/capabilitypatterns/software_design_slot_D1C3FAF5.html"];
contentPage.processPage.elementUrls["_Viv68NOLEdyqlogshP8l4g"] = ["Implement Tests","process.openup.base/capabilitypatterns/implement_tests_ECF4B2BA.html"];
contentPage.processPage.elementUrls["_AVhA0tOOEdyqlogshP8l4g"] = ["Create Test Cases","process.openup.base/capabilitypatterns/create_test_cases_254C726.html"];
contentPage.processPage.elementUrls["_sopKYNOJEdyqlogshP8l4g"] = ["Develop Technical Vision","process.openup.base/capabilitypatterns/develop_technical_vision_89F6E7DB.html"];
contentPage.processPage.elementUrls["_EOwqoNOLEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_3FC85194.html"];
contentPage.processPage.elementUrls["_BWWIgdOKEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_6A535494.html"];
contentPage.processPage.elementUrls["_pzQU0dONEdyqlogshP8l4g"] = ["Transition Phase Iteration","process.openup.base/capabilitypatterns/transition_phase_iteration_57B0A6B5.html"];
contentPage.processPage.elementUrls["_Viv68dOLEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_DB8DC6D0.html"];
contentPage.processPage.elementUrls["_eWxZgdOEEdyqlogshP8l4g"] = ["Initiate Project","process.openup.base/capabilitypatterns/initiate_project_37A47ADB.html"];
contentPage.processPage.elementUrls["_-UFkUVThEd2ZeY-22kx0mw"] = ["Inception Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Inception Phase_5078703C.html"];
contentPage.processPage.elementUrls["_iRZNQNOKEdyqlogshP8l4g"] = ["Run Developer Tests","process.openup.base/capabilitypatterns/run_developer_tests_91CCE06A.html"];
contentPage.processPage.elementUrls["_6RuKMN_1EdyOsumnGvWsEg"] = ["Refine the Architecture","process.openup.base/capabilitypatterns/refine_the_arch_42A35209.html"];
contentPage.processPage.elementUrls["_EOwqodOLEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_2E6165AA.html"];
contentPage.processPage.elementUrls["_WjtCIO-ZEdyEMtC_IfEALw"] = ["Any Role","process.openup.base/capabilitypatterns/any_role_3D41C9C6.html"];
contentPage.processPage.elementUrls["_y1MMMNOJEdyqlogshP8l4g"] = ["Iteration Plan","process.openup.base/capabilitypatterns/iteration_plan_5D6BAD68.html"];
contentPage.processPage.elementUrls["_HhjJsdOOEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_48F8F25.html"];
contentPage.processPage.elementUrls["_6RuKMd_1EdyOsumnGvWsEg"] = ["Developer","process.openup.base/capabilitypatterns/developer_313C661F.html"];
contentPage.processPage.elementUrls["_FX7SINOLEdyqlogshP8l4g"] = ["Detail Use-Case Scenarios","process.openup.base/capabilitypatterns/detail_use_case_scenarios_79A10C4.html"];
contentPage.processPage.elementUrls["_EOwqqNOLEdyqlogshP8l4g"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_C8EC15D2.html"];
contentPage.processPage.elementUrls["_t7pDUdOJEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_8BAFCD95.html"];
contentPage.processPage.elementUrls["_soyUU9OJEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_718842B.html"];
contentPage.processPage.elementUrls["_BWf5gtOKEdyqlogshP8l4g"] = ["Architecture Notebook","process.openup.base/capabilitypatterns/architecture_notebook_F61D2121.html"];
contentPage.processPage.elementUrls["_HGqkMdnTEdyNj6EOmqy5Rg"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_A8A07014.html"];
contentPage.processPage.elementUrls["_oZgCsdOEEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_F9713A62.html"];
contentPage.processPage.elementUrls["_AVhA0dOOEdyqlogshP8l4g"] = ["Detail System-Wide Requirements","process.openup.base/capabilitypatterns/detail_system_wide_requirements_F7B6E716.html"];
contentPage.processPage.elementUrls["_XayTQdOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_947FDB8B.html"];
contentPage.processPage.elementUrls["_y1MMM9OJEdyqlogshP8l4g"] = ["[Technical Architecture]","process.openup.base/capabilitypatterns/technical_architecture_slot_BF7C7753.html"];
contentPage.processPage.elementUrls["_n75CddfeEdy8T_PKWvNDBA"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_7136EBED.html"];
contentPage.processPage.elementUrls["_Viv69NOLEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_B18694D9.html"];
contentPage.processPage.elementUrls["_gXo2UNOKEdyqlogshP8l4g"] = ["Implement Developer Tests","process.openup.base/capabilitypatterns/implement_developer_tests_6442995D.html"];
contentPage.processPage.elementUrls["_5v_o4dOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_1EC56795.html"];
contentPage.processPage.elementUrls["_frYNRNOKEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_6E4A6C6D.html"];
contentPage.processPage.elementUrls["_EOwqqdOLEdyqlogshP8l4g"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_B78529E8.html"];
contentPage.processPage.elementUrls["_AP_nodOOEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_E4A7147.html"];
contentPage.processPage.elementUrls["_dC4w4JojEd2XAqcHTC2Siw"] = ["Implementation","process.openup.base/capabilitypatterns/implementation_1DA9E76A.html"];
contentPage.processPage.elementUrls["_uxDPEdOOEdyqlogshP8l4g"] = ["Plan and Manage Iteration","process.openup.base/capabilitypatterns/plan_manage_iteration_91628C02.html"];
contentPage.processPage.elementUrls["_AQJYoNOOEdyqlogshP8l4g"] = ["Identify and Outline Requirements","process.openup.base/capabilitypatterns/identify_and_outline_requirements_4D09B812.html"];
contentPage.processPage.elementUrls["_SuWj4dOPEdyqlogshP8l4g"] = ["OpenUP Lifecycle","process.openup.base/deliveryprocesses/openup_lifecycle_EE511F3A.html"];
contentPage.processPage.elementUrls["_6RuKMt_1EdyOsumnGvWsEg"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_3BDA462F.html"];
contentPage.processPage.elementUrls["_n75CcdfeEdy8T_PKWvNDBA"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_ACA509CE.html"];
contentPage.processPage.elementUrls["_KaeNsdOFEdyqlogshP8l4g"] = ["Develop the Architecture","process.openup.base/capabilitypatterns/develop_architecture_C7BBA35B.html"];
contentPage.processPage.elementUrls["_EOwqptOLEdyqlogshP8l4g"] = ["System-WideRequirements","process.openup.base/capabilitypatterns/system_wide_requirements_FD9127D9.html"];
contentPage.processPage.elementUrls["_XJ0u0FTiEd2ZeY-22kx0mw"] = ["Lifecycle Architecture Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Lifecycle Architecture Milestone_65437D7C.html"];
contentPage.processPage.elementUrls["_n75CdNfeEdy8T_PKWvNDBA"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_829DD7D7.html"];
contentPage.processPage.elementUrls["_y1CbMNOJEdyqlogshP8l4g"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_30135287.html"];
contentPage.processPage.elementUrls["_CqFrgdOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_2E5A12EB.html"];
contentPage.processPage.elementUrls["_frh-QdOKEdyqlogshP8l4g"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_A7D69414.html"];
contentPage.processPage.elementUrls["_frYNQdOKEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_98519E64.html"];
contentPage.processPage.elementUrls["_BBN48VTiEd2ZeY-22kx0mw"] = ["Transition Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Transition Phase_8CDF05F3.html"];
contentPage.processPage.elementUrls["_0Qiv4NOJEdyqlogshP8l4g"] = ["Assess Results","process.openup.base/capabilitypatterns/assess_results_A8262B77.html"];
contentPage.processPage.elementUrls["_hVe-oNOKEdyqlogshP8l4g"] = ["Implement Solution","process.openup.base/capabilitypatterns/implement_solution_B7C117A5.html"];
contentPage.processPage.elementUrls["_LxTaQNnGEdyNWvE4rz3mXQ"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_DDD377AB.html"];
contentPage.processPage.elementUrls["_EOwqp9OLEdyqlogshP8l4g"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_666AFD9E.html"];
contentPage.processPage.elementUrls["_eyv_UdOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_C9559260.html"];
contentPage.processPage.elementUrls["_nfpBkVQwEd2i9JHp7xurvw"] = ["Construction Phase","process.openup.base/deliveryprocesses/Construction Phase_BD0D5748.html"];
contentPage.processPage.elementUrls["_OpsH8GpmEd24CboUCnKL3A"] = ["Glossary","process.openup.base/capabilitypatterns/glossary_559BC141.html"];
contentPage.processPage.elementUrls["_AQJYo9OOEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_AF1A81FD.html"];
contentPage.processPage.elementUrls["_aJ1X4No7EdyzZqGyZ7hwdw"] = ["Build","process.openup.base/capabilitypatterns/build_309F83F9.html"];
contentPage.processPage.elementUrls["_Dlo8wNo8EdyzZqGyZ7hwdw"] = ["Integrate and Create Build","process.openup.base/capabilitypatterns/integrate_and_create_build_CFB94658.html"];
contentPage.processPage.elementUrls["_WttSMdOLEdyqlogshP8l4g"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_89A700A4.html"];
contentPage.processPage.elementUrls["_-AGJcO-YEdyEMtC_IfEALw"] = ["[Project Definition and Scope]","process.openup.base/capabilitypatterns/project_definition_and_scope_slot_ABFD6480.html"];
contentPage.processPage.elementUrls["_wU5YkG7rEd2yFK8n6tDvyw"] = ["[Project Work]","process.openup.base/capabilitypatterns/project_work_slot_B5F50387.html"];
contentPage.processPage.elementUrls["_Vi5r8dOLEdyqlogshP8l4g"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_3F6541ED.html"];
contentPage.processPage.elementUrls["_6R37Md_1EdyOsumnGvWsEg"] = ["[Software Design]","process.openup.base/capabilitypatterns/software_design_slot_68337E8D.html"];
contentPage.processPage.elementUrls["_frYNQtOKEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_A2EF7E74.html"];
contentPage.processPage.elementUrls["_LxTaQdnGEdyNWvE4rz3mXQ"] = ["[Technical Test Results]","process.openup.base/capabilitypatterns/technical_test_results_slot_CC6C8BC1.html"];
contentPage.processPage.elementUrls["_F68foNOLEdyqlogshP8l4g"] = ["Detail System-Wide Requirements","process.openup.base/capabilitypatterns/detail_system_wide_requirements_B4381DEE.html"];
contentPage.processPage.elementUrls["_SKnAxOL9EdyM47cGD2jiaQ"] = ["Transition Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Transition Iteration 1..n_D89697C5.html"];
contentPage.processPage.elementUrls["_AQJYqtOOEdyqlogshP8l4g"] = ["Use-Case Model","process.openup.base/capabilitypatterns/use_case_model_CF647076.html"];
contentPage.processPage.elementUrls["_frYNQ9OKEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_BC95439.html"];
contentPage.processPage.elementUrls["_6R37Mt_1EdyOsumnGvWsEg"] = ["[Software Implementation]","process.openup.base/capabilitypatterns/software_implementation_slot_72D15E9D.html"];
contentPage.processPage.elementUrls["_t7pDUNOJEdyqlogshP8l4g"] = ["Plan Project","process.openup.base/capabilitypatterns/plan_the_project_9D16B97F.html"];
contentPage.processPage.elementUrls["_g8cPsdOOEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_6EA48E23.html"];
contentPage.processPage.elementUrls["_Bn6qoFQ0Ed2i9JHp7xurvw"] = ["Lifecycle Architecture Milestone","process.openup.base/deliveryprocesses/lifecycle_architecture_milestone_6645814A.html"];
contentPage.processPage.elementUrls["_sjccUN_1EdyOsumnGvWsEg"] = ["Outline the Architecture","process.openup.base/capabilitypatterns/outline_the_arch_A1FEF666.html"];
contentPage.processPage.elementUrls["_soyUUNOJEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_A507BA40.html"];
contentPage.processPage.elementUrls["_y1CbNdOJEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_E33E48BC.html"];
contentPage.processPage.elementUrls["_w-Bc8dOOEdyqlogshP8l4g"] = ["Agree on Technical Approach","process.openup.base/capabilitypatterns/agree_technical_approach_66972D77.html"];
contentPage.processPage.elementUrls["_frYNQNOKEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_A9B88A4E.html"];
contentPage.processPage.elementUrls["_CoJVUdOPEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_BCA6545C.html"];
contentPage.processPage.elementUrls["_nfpeAdOOEdyqlogshP8l4g"] = ["Initiate Project","process.openup.base/capabilitypatterns/initiate_project_9D7C8344.html"];
contentPage.processPage.elementUrls["_AVhA0NOOEdyqlogshP8l4g"] = ["Detail Use-Case Scenarios","process.openup.base/capabilitypatterns/detail_use_case_scenarios_91DD300.html"];
contentPage.processPage.elementUrls["_Dlo8wdo8EdyzZqGyZ7hwdw"] = ["Test Script","process.openup.base/capabilitypatterns/test_script_BE525A6E.html"];
contentPage.processPage.elementUrls["_TUrpQFTiEd2ZeY-22kx0mw"] = ["Lifecycle Objectives Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Lifecycle Objectives Milestone_DFF2A143.html"];
contentPage.processPage.elementUrls["_AQJYpNOOEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_119B9A31.html"];
contentPage.processPage.elementUrls["_EOwqotOLEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_38FF45BA.html"];
contentPage.processPage.elementUrls["_AQJYqNOOEdyqlogshP8l4g"] = ["Use Case","process.openup.base/capabilitypatterns/use_case_D62D7C50.html"];
contentPage.processPage.elementUrls["_gX7xQNOKEdyqlogshP8l4g"] = ["[Software Implementation]","process.openup.base/capabilitypatterns/software_implementation_slot_E32AE6DF.html"];
contentPage.processPage.elementUrls["_-iix4dOOEdyqlogshP8l4g"] = ["Develop Solution Increment","process.openup.base/capabilitypatterns/develop_solution_8E22EA8F.html"];
contentPage.processPage.elementUrls["_EfWx0FQ0Ed2i9JHp7xurvw"] = ["Initial Operational Capability Milestone","process.openup.base/deliveryprocesses/initial_operational_capability_milestone_B0ADAE04.html"];
contentPage.processPage.elementUrls["_4ypNIO-YEdyEMtC_IfEALw"] = ["Project Plan","process.openup.base/capabilitypatterns/project_plan_73DF1826.html"];
contentPage.processPage.elementUrls["_y1MMMdOJEdyqlogshP8l4g"] = ["Risk List","process.openup.base/capabilitypatterns/risk_list_4C04C17E.html"];
contentPage.processPage.elementUrls["__ZInMdOEEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_CA154C21.html"];
contentPage.processPage.elementUrls["_AQJYpdOOEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_34AE47.html"];
contentPage.processPage.elementUrls["_EOwqpNOLEdyqlogshP8l4g"] = ["Tester","process.openup.base/capabilitypatterns/tester_45A33B3.html"];
contentPage.processPage.elementUrls["_YwLY4dOOEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_38854BCF.html"];
contentPage.processPage.elementUrls["_nm0swFTiEd2ZeY-22kx0mw"] = ["Product Release Milestone","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Product Release Milestone_96CC0AE0.html"];
contentPage.processPage.elementUrls["_dC4w4ZojEd2XAqcHTC2Siw"] = ["Test Log","process.openup.base/capabilitypatterns/test_log_2847C77A.html"];
contentPage.processPage.elementUrls["_HDOWUtOLEdyqlogshP8l4g"] = ["Test Case","process.openup.base/capabilitypatterns/test_case_36958574.html"];
contentPage.processPage.elementUrls["_zjF0ANOJEdyqlogshP8l4g"] = ["Manage Iteration","process.openup.base/capabilitypatterns/manage_iteration_D96F88D6.html"];
contentPage.processPage.elementUrls["_AQJYotOOEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_4640AC38.html"];
contentPage.processPage.elementUrls["_GQejYdOOEdyqlogshP8l4g"] = ["Ongoing Tasks","process.openup.base/capabilitypatterns/ongoing_tasks_949DD70E.html"];
contentPage.processPage.elementUrls["_EOm5oNOLEdyqlogshP8l4g"] = ["Identify and Outline Requirements","process.openup.base/capabilitypatterns/identify_and_outline_requirements_FF8708A2.html"];
contentPage.processPage.elementUrls["_n75CctfeEdy8T_PKWvNDBA"] = ["Developer","process.openup.base/capabilitypatterns/developer_B742E9DE.html"];
contentPage.processPage.elementUrls["_aSrtcdOOEdyqlogshP8l4g"] = ["Develop the Architecture","process.openup.base/capabilitypatterns/develop_architecture_D0F73FC9.html"];
contentPage.processPage.elementUrls["_y1CbMdOJEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_1EAC669D.html"];
contentPage.processPage.elementUrls["_n75Cc9feEdy8T_PKWvNDBA"] = ["Project Manager","process.openup.base/capabilitypatterns/project_manager_201CBFA3.html"];
contentPage.processPage.elementUrls["_SKnA1uL9EdyM47cGD2jiaQ"] = ["Risk-Value Lifecycle Phases","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/risk_value_lifecycle_phases_4D57D552.html"];
contentPage.processPage.elementUrls["_buG4sdOFEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_D16D88FC.html"];
contentPage.processPage.elementUrls["_pOgXIVQwEd2i9JHp7xurvw"] = ["Transition Phase","process.openup.base/deliveryprocesses/Transition Phase_14EE9310.html"];
contentPage.processPage.elementUrls["_vyeP0dOOEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_E06651D6.html"];
contentPage.processPage.elementUrls["_SKnAyOL9EdyM47cGD2jiaQ"] = ["Construction Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Construction Iteration 1..n_9D2879E4.html"];
contentPage.processPage.elementUrls["_f4VuYdOOEdyqlogshP8l4g"] = ["Test Solution","process.openup.base/capabilitypatterns/test_solution_B552446C.html"];
contentPage.processPage.elementUrls["_y1MMMtOJEdyqlogshP8l4g"] = ["Work Items List","process.openup.base/capabilitypatterns/work_items_list_56A2A18E.html"];
contentPage.processPage.elementUrls["_soyUUdOJEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_93A0CE56.html"];
contentPage.processPage.elementUrls["_AQJYp9OOEdyqlogshP8l4g"] = ["System-WideRequirements","process.openup.base/capabilitypatterns/system_wide_requirements_73AC641C.html"];
contentPage.processPage.elementUrls["_Viv68tOLEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_E62BA6E0.html"];
contentPage.processPage.elementUrls["_7bg6EdOPEdyqlogshP8l4g"] = ["Transition Iteration [1..n]","process.openup.base/deliveryprocesses/transition_phase_iteration_9880C0E.html"];
contentPage.processPage.elementUrls["_8tQrUVQvEd2i9JHp7xurvw"] = ["Inception Phase","process.openup.base/deliveryprocesses/Inception Phase_5229EC90.html"];
contentPage.processPage.elementUrls["_mqtdUFQzEd2i9JHp7xurvw"] = ["Lifecycle Objectives Milestone","process.openup.base/deliveryprocesses/lifecycle_objectives_milestone_CEAD6E5B.html"];
contentPage.processPage.elementUrls["_Viv689OLEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_4F057CA5.html"];
contentPage.processPage.elementUrls["_frOcQNOKEdyqlogshP8l4g"] = ["Design the Solution","process.openup.base/capabilitypatterns/design_solution_7C602F6D.html"];
contentPage.processPage.elementUrls["_4ouDUdOEEdyqlogshP8l4g"] = ["Agree on Technical Approach","process.openup.base/capabilitypatterns/agree_technical_approach_7096F6A3.html"];
contentPage.processPage.elementUrls["_AQJYodOOEdyqlogshP8l4g"] = ["Analyst","process.openup.base/capabilitypatterns/analyst_3BA2CC28.html"];
contentPage.processPage.elementUrls["_Vi5r8tOLEdyqlogshP8l4g"] = ["[Software Implementation]","process.openup.base/capabilitypatterns/software_implementation_slot_4A0321FD.html"];
contentPage.processPage.elementUrls["_6R37MN_1EdyOsumnGvWsEg"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_799A6A77.html"];
contentPage.processPage.elementUrls["_frh-QNOKEdyqlogshP8l4g"] = ["[Technical Architecture]","process.openup.base/capabilitypatterns/technical_architecture_slot_B93D7FFE.html"];
contentPage.processPage.elementUrls["_ILZlwFQ0Ed2i9JHp7xurvw"] = ["Product Release Milestone","process.openup.base/deliveryprocesses/product_release_milestone_1A9A4E10.html"];
contentPage.processPage.elementUrls["_HDOWUdOLEdyqlogshP8l4g"] = ["[Technical Specification]","process.openup.base/capabilitypatterns/technical_specification_slot_2BF7A564.html"];
contentPage.processPage.elementUrls["_y1CbMtOJEdyqlogshP8l4g"] = ["Architect","process.openup.base/capabilitypatterns/architect_294A46AD.html"];
contentPage.processPage.elementUrls["_y1CbNNOJEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_F4A534A6.html"];
contentPage.processPage.elementUrls["_51ewYdOPEdyqlogshP8l4g"] = ["Elaboration Iteration [1..n]","process.openup.base/deliveryprocesses/elaboration_phase_iteration_579A68CE.html"];
contentPage.processPage.elementUrls["_xxcpgdOEEdyqlogshP8l4g"] = ["Identify and Refine Requirements","process.openup.base/capabilitypatterns/identify_and_refine_requirements_7FA6CB14.html"];
contentPage.processPage.elementUrls["_HDOWUNOLEdyqlogshP8l4g"] = ["Create Test Cases","process.openup.base/capabilitypatterns/create_test_cases_3D5E914E.html"];
contentPage.processPage.elementUrls["_WttSMNOLEdyqlogshP8l4g"] = ["Run Tests","process.openup.base/capabilitypatterns/run_tests_9B0DEC8E.html"];
contentPage.processPage.elementUrls["_y1CbM9OJEdyqlogshP8l4g"] = ["Developer","process.openup.base/capabilitypatterns/developer_92241C72.html"];
contentPage.processPage.elementUrls["_EOwqo9OLEdyqlogshP8l4g"] = ["Stakeholder","process.openup.base/capabilitypatterns/stakeholder_A1D91B7F.html"];
contentPage.processPage.elementUrls["__r658VThEd2ZeY-22kx0mw"] = ["Construction Phase","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Construction Phase_E35610BE.html"];
contentPage.processPage.elementUrls["_SKnA0uL9EdyM47cGD2jiaQ"] = ["Elaboration Iteration [1..n]","practice.mgmt.risk_value_lifecycle.base/capabilitypatterns/Elaboration Iteration 1..n_88C5F333.html"];
